-- MySQL Script generated by MySQL Workbench
-- Fri Dec 10 04:33:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apteka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apteka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apteka` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `apteka` ;

-- -----------------------------------------------------
-- Table `apteka`.`сп_должн`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`сп_должн` (
  `код` INT NOT NULL AUTO_INCREMENT,
  `должность` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`),
  UNIQUE INDEX `должность_UNIQUE` (`должность` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`сп_подразд`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`сп_подразд` (
  `код` INT NOT NULL,
  `подразделение` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`),
  UNIQUE INDEX `подразделение_UNIQUE` (`подразделение` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`сп_сотр`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`сп_сотр` (
  `код` INT NOT NULL,
  `наимСотр` VARCHAR(45) NOT NULL,
  `должность` VARCHAR(45) NOT NULL,
  `подразделение` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`, `должность`),
  UNIQUE INDEX `наимСотр_UNIQUE` (`наимСотр` ASC) VISIBLE,
  INDEX `подразделение_idx` (`подразделение` ASC) VISIBLE,
  INDEX `должность_idx` (`должность` ASC) VISIBLE,
  CONSTRAINT `подразделение`
    FOREIGN KEY (`подразделение`)
    REFERENCES `apteka`.`сп_подразд` (`подразделение`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `должность`
    FOREIGN KEY (`должность`)
    REFERENCES `apteka`.`сп_должн` (`должность`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`сп_едХран`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`сп_едХран` (
  `код` INT NOT NULL,
  `наимЕдХран` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`сп_производ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`сп_производ` (
  `код` INT NOT NULL,
  `производитель` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`),
  UNIQUE INDEX `производитель_UNIQUE` (`производитель` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`сп_фармТовар`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`сп_фармТовар` (
  `код` INT NOT NULL,
  `наимФармПрод` VARCHAR(45) NOT NULL,
  `производитель` VARCHAR(45) NOT NULL,
  `описание` VARCHAR(200) NOT NULL,
  `едХран` INT NOT NULL,
  PRIMARY KEY (`код`, `едХран`, `производитель`),
  INDEX `производитель_idx` (`производитель` ASC) VISIBLE,
  INDEX `fk_сп_фармТовар_сп_едХран1_idx` (`едХран` ASC) VISIBLE,
  UNIQUE INDEX `наимФармПрод_UNIQUE` (`наимФармПрод` ASC) VISIBLE,
  CONSTRAINT `производитель`
    FOREIGN KEY (`производитель`)
    REFERENCES `apteka`.`сп_производ` (`производитель`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_сп_фармТовар_сп_едХран1`
    FOREIGN KEY (`едХран`)
    REFERENCES `apteka`.`сп_едХран` (`код`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`од_картСклУчета`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`од_картСклУчета` (
  `код` INT NOT NULL,
  `наимОрг` VARCHAR(45) NOT NULL,
  `дата` DATE NOT NULL,
  `докОсн` VARCHAR(45) NOT NULL,
  `наимТовара` VARCHAR(45) NOT NULL,
  `начОстаток` INT NOT NULL,
  `конОстаток` INT NOT NULL,
  `приход` INT NULL,
  `расход` INT NULL,
  `наимСотр` VARCHAR(45) NOT NULL,
  `должнСотр` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`, `наимТовара`, `должнСотр`, `наимСотр`),
  UNIQUE INDEX `наимТовара_UNIQUE` (`наимТовара` ASC) VISIBLE,
  UNIQUE INDEX `наимСотр_UNIQUE` (`наимСотр` ASC) VISIBLE,
  INDEX `наимДолж_idx` (`должнСотр` ASC) VISIBLE,
  CONSTRAINT `наимСотр`
    FOREIGN KEY (`наимСотр`)
    REFERENCES `apteka`.`сп_сотр` (`наимСотр`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `должнСотр`
    FOREIGN KEY (`должнСотр`)
    REFERENCES `apteka`.`сп_должн` (`должность`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `товар`
    FOREIGN KEY (`наимТовара`)
    REFERENCES `apteka`.`сп_фармТовар` (`наимФармПрод`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`од_инвОпись`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`од_инвОпись` (
  `код` INT NOT NULL,
  `наимОрг` VARCHAR(45) NOT NULL,
  `дата` DATE NOT NULL,
  `докОсн` VARCHAR(45) NOT NULL,
  `наимТовара` VARCHAR(45) NOT NULL,
  `фактКол` INT NOT NULL,
  `фактОст` INT NOT NULL,
  `бухКол` INT NOT NULL,
  `бухОст` INT NOT NULL,
  `недКол` INT NOT NULL,
  `недСтоим` INT NOT NULL,
  `излКол` INT NOT NULL,
  `излСтоим` INT NOT NULL,
  `наимСотр` VARCHAR(45) NOT NULL,
  `должнСотр` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`, `наимСотр`, `должнСотр`, `наимТовара`),
  UNIQUE INDEX `наимТовара_UNIQUE` (`наимТовара` ASC) VISIBLE,
  UNIQUE INDEX `наимСотр_UNIQUE` (`наимСотр` ASC) VISIBLE,
  INDEX `наимДолж_idx` (`должнСотр` ASC) VISIBLE,
  CONSTRAINT `наимСотр2`
    FOREIGN KEY (`наимСотр`)
    REFERENCES `apteka`.`сп_сотр` (`наимСотр`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `должнСотр2`
    FOREIGN KEY (`должнСотр`)
    REFERENCES `apteka`.`сп_должн` (`должность`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `товар2`
    FOREIGN KEY (`наимТовара`)
    REFERENCES `apteka`.`сп_фармТовар` (`наимФармПрод`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`од_ОСВ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apteka`.`од_ОСВ` (
  `код` INT NOT NULL,
  `наимОрг` VARCHAR(45) NOT NULL,
  `дата` DATE NOT NULL,
  `датаС` DATE NOT NULL,
  `датаПо` DATE NOT NULL,
  `наимТовара` VARCHAR(45) NOT NULL,
  `начОстаток` INT NOT NULL,
  `конОстаток` INT NOT NULL,
  `приход` INT NULL,
  `расход` INT NULL,
  `наимСотр` VARCHAR(45) NOT NULL,
  `должнСотр` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`код`, `наимСотр`, `должнСотр`, `наимТовара`),
  UNIQUE INDEX `наимТовара_UNIQUE` (`наимТовара` ASC) VISIBLE,
  UNIQUE INDEX `наимСотр_UNIQUE` (`наимСотр` ASC) VISIBLE,
  INDEX `наимДолж_idx` (`должнСотр` ASC) VISIBLE,
  CONSTRAINT `наимСотр1`
    FOREIGN KEY (`наимСотр`)
    REFERENCES `apteka`.`сп_сотр` (`наимСотр`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `должнСотр1`
    FOREIGN KEY (`должнСотр`)
    REFERENCES `apteka`.`сп_должн` (`должность`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `товар1`
    FOREIGN KEY (`наимТовара`)
    REFERENCES `apteka`.`сп_фармТовар` (`наимФармПрод`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
