# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Leaderboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        Dialog.setStyleSheet("background-color: rgb(60, 53, 46);")
        self.textLeaderboard = QtWidgets.QLabel(Dialog)
        self.textLeaderboard.setGeometry(QtCore.QRect(180, 10, 280, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLeaderboard.sizePolicy().hasHeightForWidth())
        self.textLeaderboard.setSizePolicy(sizePolicy)
        self.textLeaderboard.setMinimumSize(QtCore.QSize(280, 40))
        self.textLeaderboard.setMaximumSize(QtCore.QSize(280, 40))
        font = QtGui.QFont()
        font.setFamily("TF2 Secondary")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.textLeaderboard.setFont(font)
        self.textLeaderboard.setStyleSheet("background-color: rgb(42, 39, 37);\n"
"border-radius: 8%;\n"
"color: rgb(109, 199, 117);")
        self.textLeaderboard.setAlignment(QtCore.Qt.AlignCenter)
        self.textLeaderboard.setObjectName("textLeaderboard")
        self.CloseButton = QtWidgets.QPushButton(Dialog)
        self.CloseButton.setGeometry(QtCore.QRect(220, 420, 200, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseButton.sizePolicy().hasHeightForWidth())
        self.CloseButton.setSizePolicy(sizePolicy)
        self.CloseButton.setMinimumSize(QtCore.QSize(200, 40))
        self.CloseButton.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("TF2")
        font.setPointSize(25)
        self.CloseButton.setFont(font)
        self.CloseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseButton.setStyleSheet("background-color: rgb(42, 39, 37);\n"
"border: 1px solid rgb(125, 109, 0);\n"
"border-radius: 8%;\n"
"color: rgb(255, 9, 1);")
        self.CloseButton.setObjectName("CloseButton")
        self.LeaderTable = QtWidgets.QTableView(Dialog)
        self.LeaderTable.setGeometry(QtCore.QRect(90, 60, 460, 350))
        self.LeaderTable.setObjectName("LeaderTable")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textLeaderboard.setText(_translate("Dialog", "Leaderboard"))
        self.CloseButton.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
