# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        Dialog.setStyleSheet("background-color: rgb(60, 53, 46);")
        self.PlayTable = QtWidgets.QTableView(Dialog)
        self.PlayTable.setGeometry(QtCore.QRect(50, 40, 300, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayTable.sizePolicy().hasHeightForWidth())
        self.PlayTable.setSizePolicy(sizePolicy)
        self.PlayTable.setMinimumSize(QtCore.QSize(300, 400))
        self.PlayTable.setMaximumSize(QtCore.QSize(300, 400))
        self.PlayTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.PlayTable.setObjectName("PlayTable")
        self.ScoreText = QtWidgets.QLabel(Dialog)
        self.ScoreText.setGeometry(QtCore.QRect(370, 60, 240, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScoreText.sizePolicy().hasHeightForWidth())
        self.ScoreText.setSizePolicy(sizePolicy)
        self.ScoreText.setMinimumSize(QtCore.QSize(240, 50))
        self.ScoreText.setMaximumSize(QtCore.QSize(240, 50))
        font = QtGui.QFont()
        font.setFamily("TF2 Secondary")
        font.setPointSize(18)
        self.ScoreText.setFont(font)
        self.ScoreText.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ScoreText.setStyleSheet("Border: 1px solid black;\n"
"border-radius: 20%;\n"
"padding: 10px;\n"
"color: rgb(255, 215, 0);")
        self.ScoreText.setObjectName("ScoreText")
        self.TimeText = QtWidgets.QLabel(Dialog)
        self.TimeText.setGeometry(QtCore.QRect(370, 130, 240, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeText.sizePolicy().hasHeightForWidth())
        self.TimeText.setSizePolicy(sizePolicy)
        self.TimeText.setMinimumSize(QtCore.QSize(240, 50))
        self.TimeText.setMaximumSize(QtCore.QSize(240, 50))
        font = QtGui.QFont()
        font.setFamily("TF2 Secondary")
        font.setPointSize(18)
        self.TimeText.setFont(font)
        self.TimeText.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.TimeText.setStyleSheet("Border: 1px solid black;\n"
"border-radius: 20%;\n"
"padding: 10px;\n"
"color: rgb(255, 215, 0);")
        self.TimeText.setObjectName("TimeText")
        self.ExitButton = QtWidgets.QPushButton(Dialog)
        self.ExitButton.setGeometry(QtCore.QRect(500, 360, 110, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitButton.sizePolicy().hasHeightForWidth())
        self.ExitButton.setSizePolicy(sizePolicy)
        self.ExitButton.setMinimumSize(QtCore.QSize(110, 50))
        self.ExitButton.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("TF2")
        font.setPointSize(25)
        self.ExitButton.setFont(font)
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ExitButton.setStyleSheet("background-color: rgb(42, 39, 37);\n"
"border: 1px solid rgb(125, 109, 0);\n"
"border-radius: 8%;\n"
"color: rgb(255, 9, 1);")
        self.ExitButton.setObjectName("ExitButton")
        self.PauseButton = QtWidgets.QPushButton(Dialog)
        self.PauseButton.setGeometry(QtCore.QRect(380, 360, 110, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PauseButton.sizePolicy().hasHeightForWidth())
        self.PauseButton.setSizePolicy(sizePolicy)
        self.PauseButton.setMinimumSize(QtCore.QSize(110, 50))
        self.PauseButton.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("TF2")
        font.setPointSize(25)
        self.PauseButton.setFont(font)
        self.PauseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PauseButton.setStyleSheet("background-color: rgb(42, 39, 37);\n"
"border: 1px solid rgb(125, 109, 0);\n"
"border-radius: 8%;\n"
"color: rgb(216, 216, 216);")
        self.PauseButton.setObjectName("PauseButton")
        self.FigureWindow = QtWidgets.QTableView(Dialog)
        self.FigureWindow.setGeometry(QtCore.QRect(510, 220, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FigureWindow.sizePolicy().hasHeightForWidth())
        self.FigureWindow.setSizePolicy(sizePolicy)
        self.FigureWindow.setMinimumSize(QtCore.QSize(100, 100))
        self.FigureWindow.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FigureWindow.setFont(font)
        self.FigureWindow.setStyleSheet("border: 1px solid rgb(125, 109, 0);\n"
"border-left: 0px;")
        self.FigureWindow.setObjectName("FigureWindow")
        self.textFigure = QtWidgets.QLabel(Dialog)
        self.textFigure.setGeometry(QtCore.QRect(370, 220, 140, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textFigure.sizePolicy().hasHeightForWidth())
        self.textFigure.setSizePolicy(sizePolicy)
        self.textFigure.setMinimumSize(QtCore.QSize(140, 100))
        self.textFigure.setMaximumSize(QtCore.QSize(140, 100))
        font = QtGui.QFont()
        font.setFamily("TF2 Secondary")
        font.setPointSize(18)
        self.textFigure.setFont(font)
        self.textFigure.setStyleSheet("color: rgb(255, 215, 0);\n"
"border: 1px solid rgb(125, 109, 0);\n"
"border-right: 0px;")
        self.textFigure.setObjectName("textFigure")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ScoreText.setText(_translate("Dialog", "Score : 0"))
        self.TimeText.setText(_translate("Dialog", "Time passed : 0"))
        self.ExitButton.setText(_translate("Dialog", "Exit"))
        self.PauseButton.setText(_translate("Dialog", "Pause"))
        self.textFigure.setText(_translate("Dialog", "Next figure : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
