# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Title.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        Dialog.setMinimumSize(QtCore.QSize(640, 480))
        Dialog.setMaximumSize(QtCore.QSize(640, 480))
        Dialog.setStyleSheet("background-color: rgb(60, 53, 46);")
        self.StartButton = QtWidgets.QPushButton(Dialog)
        self.StartButton.setGeometry(QtCore.QRect(200, 200, 240, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setMinimumSize(QtCore.QSize(240, 60))
        self.StartButton.setMaximumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setFamily("TF2")
        font.setPointSize(25)
        self.StartButton.setFont(font)
        self.StartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartButton.setStyleSheet("background-color: rgb(42, 39, 37);\n"
"border: 1px solid rgb(125, 109, 0);\n"
"border-radius: 8%;\n"
"color: rgb(255, 215, 0);")
        self.StartButton.setObjectName("StartButton")
        self.textTetris = QtWidgets.QLabel(Dialog)
        self.textTetris.setGeometry(QtCore.QRect(160, 70, 320, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textTetris.sizePolicy().hasHeightForWidth())
        self.textTetris.setSizePolicy(sizePolicy)
        self.textTetris.setMinimumSize(QtCore.QSize(320, 60))
        self.textTetris.setMaximumSize(QtCore.QSize(320, 60))
        font = QtGui.QFont()
        font.setFamily("TF2 Secondary")
        font.setPointSize(46)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.textTetris.setFont(font)
        self.textTetris.setStyleSheet("color: rgb(255, 215, 0);")
        self.textTetris.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textTetris.setAlignment(QtCore.Qt.AlignCenter)
        self.textTetris.setObjectName("textTetris")
        self.LeaderButton = QtWidgets.QPushButton(Dialog)
        self.LeaderButton.setGeometry(QtCore.QRect(200, 280, 240, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeaderButton.sizePolicy().hasHeightForWidth())
        self.LeaderButton.setSizePolicy(sizePolicy)
        self.LeaderButton.setMinimumSize(QtCore.QSize(240, 60))
        self.LeaderButton.setMaximumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setFamily("TF2")
        font.setPointSize(25)
        self.LeaderButton.setFont(font)
        self.LeaderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LeaderButton.setStyleSheet("background-color: rgb(42, 39, 37);\n"
"border: 1px solid rgb(125, 109, 0);\n"
"border-radius: 8%;\n"
"color: rgb(109, 199, 117);")
        self.LeaderButton.setObjectName("LeaderButton")
        self.ExitButton = QtWidgets.QPushButton(Dialog)
        self.ExitButton.setGeometry(QtCore.QRect(220, 360, 200, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitButton.sizePolicy().hasHeightForWidth())
        self.ExitButton.setSizePolicy(sizePolicy)
        self.ExitButton.setMinimumSize(QtCore.QSize(200, 60))
        self.ExitButton.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("TF2")
        font.setPointSize(25)
        self.ExitButton.setFont(font)
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ExitButton.setStyleSheet("background-color: rgb(42, 39, 37);\n"
"border: 1px solid rgb(125, 109, 0);\n"
"border-radius: 8%;\n"
"color: rgb(255, 9, 1);")
        self.ExitButton.setObjectName("ExitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.StartButton.setText(_translate("Dialog", "Start"))
        self.textTetris.setText(_translate("Dialog", "Tetris"))
        self.LeaderButton.setText(_translate("Dialog", "Leaderboard"))
        self.ExitButton.setText(_translate("Dialog", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
